### PR TITLE
Issue 128 - Fix to incorrect table layout with rowSpan and colSpan

### PR DESCRIPTION
**Pull request by speedytwenty**
I was having a similar issue as that described in #128. This PR resolves the issue and adds a test that covers the use case.

### CODE REVIEW

**Comment by nimit2801** [comment]
I'll surely try this thank you.

**Comment by nimit2801** [comment]
This solves #211. Thanks @speedytwenty.

**Comment by speedytwenty** [comment]
Wanted to call this PR to your attention in case you may find time to review it @Turbo87 @DanielRuf 

This resolves the 3 mentioned issues (#128 #147 #211) and includes an appropriate unit test.

**Comment by speedytwenty** [comment]
I rebased the branch to make it an easy fast-forward.

**Review by DanielRuf — APPROVED** [review]

**Comment by speedytwenty** [comment]
Fixed with: 6cfb6e0

**Pull request closed without merging**
